version: '3'

services:
  db:
    image: postgres:14
    container_name: db
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    tty: true
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env

  psql:
    image: postgres:14
    container_name: psql
    depends_on:
      - db
    environment:
      - PGPASSWORD=${POSTGRES_PASSWORD}
    tty: true
    entrypoint: [ "/bin/bash", "-c" ]
    command: >
      sh -c 'while ! psql "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}?sslmode=require" -c "select 1" > /dev/null 2>&1; do
        echo "Waiting for database connection..."
        sleep 1
      done'